"""updates

Revision ID: 12cbc6307483
Revises: 
Create Date: 2024-12-04 18:56:15.018601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12cbc6307483'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_white', sa.Integer(), nullable=False),
    sa.Column('player_black', sa.Integer(), nullable=True),
    sa.Column('board_state', sa.Text(), nullable=False),
    sa.Column('turn', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('moves', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['player_black'], ['user.id'], ),
    sa.ForeignKeyConstraint(['player_white'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('user')
    # ### end Alembic commands ###
